### ISSUE TITLE
webhookUrl field error on simple payment capture.

### ISSUE THREAD

**Issue by tudorradubarbu** [BitBagCommerce/SyliusMolliePlugin#11]
I have installed the plugin and tried to make a small payment. I receive this:

<img width="1090" alt="Screen Shot 2019-09-05 at 16 33 33" src="https://user-images.githubusercontent.com/46892552/64351704-19512500-cffb-11e9-98bd-dbe4b01a662b.png">

What I am missing here?

**Comment by Emilvooo** [comment]
Its because Mollie is unable to reach your webhook, because Mollie cant make a call to your localhost :) What i did is comment the 'webhookUrl' in `vendor/bitbag/mollie-plugin/src/Action/CaptureAction.php`
