### ISSUE TITLE
[Bug] Start of Mollie transaction with a POST request

### ISSUE THREAD

**Issue by wimulkeman** [BitBagCommerce/SyliusMolliePlugin#12]
In the current implementation a POST redirect is used to start the transaction interface of Mollie. Implementing this resulted in the message "Het formulier is verlopen, probeer het opnieuw". This translates from Dutch to English in "The form expired, try again".

The tech support of Mollie pointed out that the redirect should be done with a GET request instead of a POST. After changing this in the project the message disappeared and the issue was resolved.

This issue was created during the upgrade to Sylius 1.4 https://github.com/BitBagCommerce/SyliusMolliePlugin/commit/b049a079c20cf6ce4b9aaf271c3a4ad0861be09f.

**Comment by willemstuursma** [comment]
This comes back regularly, any ideas how we could make this more clear in our documentation?

**Comment by wimulkeman** [comment]
After been pointed at the error and your comment I dived into the documentation of the Mollie API at https://github.com/mollie/mollie-api-php and https://docs.mollie.com/payments/overview. In the docs it is stated neatly that using a POST will generate errors. So it should be possible to backtrace the problem.

However I think the problem presents itself in a couple of ways:
- When someone uses this plugin they would expect it to work out of the box. Especially because it is listed on the Mollie packages page https://www.mollie.com/nl/developers/packages. So when a error occurrences a developer will assume it must be related to the key or something (thats what I though at first).
- Aldo it is stated clearly in the docs, and a little less obvious in the Github README, there is no description of what the error is which a user will see. Because of that it can't be found during a Google debug session.
- The error in itself is not helpful for it stated that the form is expired. I found a reference to the error in a forum post of October 2018 but that was the only mentioning of it on the internet. Documenting the errors which can be thrown and the cause of it would help quiet a lot for it would guide in the right direction to find the cause of the error.

But above all such a bug should not be held dwelling for so long in a plugin. Hopefully this or the other standing pull request will be merged soon so that it will work again in a normal fashion.

@bitbager Would it be possible to prioritise merging the pull request? For now I overwrote the service and replace the HttpPostRedirect exception using a try/catch with a HttpRedirect, but it would be nice to use the plugin on its own.

**Comment by wimulkeman** [comment]
@bitbager Could you look at this? This is a pending problem which impacts conversion for sites for it shows an error during payment but can be fixed with a small code update provided by the pull request.

If there are additional updates required I could help with that.
