### ISSUE TITLE
Issues trying the plugin

### ISSUE THREAD

**Issue by tavy315** [BitBagCommerce/SyliusMolliePlugin#14]
Getting this error when trying to edit any payment method:
```
Neither the property "mollieGatewayConfig" nor one of the methods "getMollieGatewayConfig()", "mollieGatewayConfig()", "isMollieGatewayConfig()", "hasMollieGatewayConfig()", "__get()" exist and have public access in class "Proxies\__CG__\App\Entity\Payment\GatewayConfig".
```

Trying to extend `BitBag\SyliusMolliePlugin\Entity\GatewayConfig` won't help since $mollieGatewayConfig is private. 

Trying to implement `BitBag\SyliusMolliePlugin\Entity\GatewayConfigInterface` generates a different error when using "Load methods":
```
Argument 1 passed to BitBag\SyliusMolliePlugin\Entity\MollieGatewayConfig::setGateway() must be an instance of BitBag\SyliusMolliePlugin\Entity\GatewayConfig, instance of App\Entity\Payment\GatewayConfig given, called in \vendor\bitbag\mollie-plugin\src\Factory\MollieGatewayConfigFactory.php on line 45
```
The interface declares `public function setGateway(GatewayConfig $gateway): void;` instead of using `GatewayConfigInterface`.

**Comment by daniel8702** [comment]
Hi, thank for Your message, it looks like I have to change class
from final to class MollieGatewayConfig.

**Comment by bchatard** [comment]
hello,

I try this (dirty?) workaround: copy / paste the content of `\BitBag\SyliusMolliePlugin\Entity\GatewayConfig` into `\App\Entity\Payment\GatewayConfig`

The error disapear, but I found another bug when I try to "load methods" (I will create a different issue for this point)

**Comment by bchatard** [comment]
hello,

I try something new this morning. 

First I revert the workaround mention previously.

Then, in `config/packages/_sylius.yaml`, I change this:
```diff
sylius_payum:
    resources:
        payment_security_token:
            classes:
                model: App\Entity\Payment\PaymentSecurityToken
        gateway_config:
            classes:
-                model: App\Entity\Payment\GatewayConfig
+                model: BitBag\SyliusMolliePlugin\Entity\GatewayConfig
+                interface: BitBag\SyliusMolliePlugin\Entity\GatewayConfigInterface
```

Plugin seems to works, the error mentioned in #15 is fixed.

But is it the right way to do this? How can we handle additional payment method from other plugins?

**Comment by tavy315** [comment]
You assume that GatewayConfig doesn't have any other changes. The functionality used in the BitBag\SyliusMolliePlugin\Entity\GatewayConfig class should be easy to be added in my GatewayConfig class via a trait. Also, where you expect to have GatewayConfig injected, expect BitBag\SyliusMolliePlugin\Entity\GatewayConfigInterface instead, because my GatewayConfig class can implement GatewayConfigInterface and problem should be solved. I will also test this.

**Comment by bchatard** [comment]
side effect or not, can't deliver to UAT (prod env), an error occurred during the cache compilation 

```
$ bin/console cache:clear

 // Clearing the cache for the prod environment with debug false

 // Warming up cache...


In InvalidArgumentException.php line 94:

  [Doctrine\Common\Proxy\Exception\InvalidArgumentException]
  Unable to create a proxy for a final class "BitBag\SyliusMolliePlugin\Entity\MollieGatewayConfig".
```
