### ISSUE TITLE
PHP 8 and Sylius 1.10

### ISSUE THREAD

**Issue by michaelKaefer** [BitBagCommerce/SyliusMolliePlugin#160]
When do you plan to add PHP 8 support? (as Sylius 1.10 supports PHP 8). Thank you for answer!

**Comment by xNordo** [comment]
Hi, PHP 8 support will be released with an update to Sylius 1.10, which we don't have a release date yet, but we will do it as soon as possible.

**Comment by Kodi-Studio** [comment]
Yep !! you need to add --ignore-platform-reqs like this : 

composer install --ignore-platform-reqs
