### ISSUE TITLE
incomplete files with composer require

### ISSUE THREAD

**Issue by JoostFaber** [BitBagCommerce/SyliusMolliePlugin#175]
Hi,

Im trying to install the SyliusMolliePlugin and i also have installed the other required plugins (AdminOrderCreate and the RefundPlugin) following your installation manual.

So far so good, but when i install this mollieplugin version ^v3.30, i am missing the following files in which i can't complete the configuration:

BitBag\SyliusMolliePlugin\Entity\OrderInterface
BitBag\SyliusMolliePlugin\Entity\OrderTrait

BitBag\SyliusMolliePlugin\Entity\ProductInterface
BitBag\SyliusMolliePlugin\Entity\ProductTrait

The GatewayConfig as provided in your installation steps doesn't give any problems. The required files are available.

your v3.3.* branch
![Mollie_plugin_tag_v3 3 10](https://user-images.githubusercontent.com/11028935/128039447-f0b37521-242c-4b91-8733-870698093c65.png)

the entity folder of the mollieplugin in my project
![product_mollieplugin_entity_folder](https://user-images.githubusercontent.com/11028935/128039482-a0cb9331-ff67-4640-9f51-f71fcf8188b6.png)

my composer.json
![composer_json](https://user-images.githubusercontent.com/11028935/128039506-677900e5-c8a7-44c6-8c9d-1f26940f0e31.png)

I am using Sylius v1.10 and Composer version 2.1.3

**Comment by michaelKaefer** [comment]
@JoostFaber The Plugin is not compatible with Sylius v1.10 (also you do not have the latest version (v3.3.10) installed but an old version (v3.3.0)). For Sylius v1.10 there already is an issue (https://github.com/BitBagCommerce/SyliusMolliePlugin/issues/160) so this issue can be closed I guess.
