### ISSUE TITLE
Missing proxy in prod mode

### ISSUE THREAD

**Issue by bchatard** [BitBagCommerce/SyliusMolliePlugin#18]
Hello,

Module version: 3.1.0
Sylius version: 1.6.4

On fresh install of Sylius + the module, then I enable production mode. 
I can configure the credentials in backend (creation), but when I want to edit the server respond with an error
``` 
Fatal error: require(): Failed opening required '/Users/bchatard/Projects/Sylius/mollie/var/cache/prod/doctrine/orm/Proxies/__CG__SyliusBundlePayumBundleModelGatewayConfig.php' (include_path='.:/usr/local/Cellar/php/7.4.6/share/php/pear') in /Users/bchatard/Projects/Sylius/mollie/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 206
```
Indeed this proxy doesn't exists in prod mode, but in dev mode it exists. If I copy the dev class into prod proxy cache it works well :)

**Comment by Sander-Voogt** [comment]
I've also this problem, did you already found a solution?
