### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null in applepayDirect.js

### ISSUE THREAD

**Issue by Zilus** [BitBagCommerce/SyliusMolliePlugin#182]
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.<anonymous> (applePayDirect.js:87)
    at mightThrow (jquery.js:3762)
    at process (jquery.js:3830)

Original  code:
```
document.querySelector('#mollie_applepay_button').addEventListener('click', (evt) => {
        applePaySession()
})
```
   The fix should be something like this: 

`const mollieApplepayButton = document.querySelector('#mollie_applepay_button');
    
    if(mollieApplepayButton) {
      mollieApplepayButton.addEventListener('click', (evt) => {
        applePaySession()
      })
    }`

**Comment by Harvel218** [comment]
Hi, thank you very much for your input and willingness to help.
The problem with this bug has already been fixed with the last Beta release.

https://github.com/BitBagCommerce/SyliusMolliePlugin/blob/20fada0b9be621dc92700b4b3b13fc31d7904485/src/Resources/assets/shop/js/mollie/applePayDirect.js#L86
