### ISSUE TITLE
Shop API Integration

### ISSUE THREAD

**Issue by pierre-H** [BitBagCommerce/SyliusMolliePlugin#19]
Hello,

First thank you for your great work !

Could you please indicate in the doc how to use this plugin with the Sylius Shop API ?

Thank you !

**Comment by nithiz** [comment]
@pierre-H Have you found a way to make it work? What i'm trying to accomplish is to simply redirect the user to the mollie payment page without having to select a payment method on my own website. Also, i can't even find the "Load methods" button, i have no idea where to find it and my Sylius interface is way different from the screenshots in the docs. As far as i've seen everything in this bundle is build around selecting a payment method on your own website, not in the Mollie "payment portal".

Thanks :)

**Comment by pierre-H** [comment]
Unfortunately no.
I've decided to give up this plugin and to use the ReactJS Stripe plugin.

**Comment by MerijnMollie** [comment]
Hi @pierre-H ,

We've decided to not implement the Shop API, as this will be deprecated[(Read more here)](https://sylius.com/blog/the-future-of-sylius-api/).
The replacement API Platform is something we'll jump on as early as possible. This seems to be released somewhere around September 2020. Keep an eye out on the releases to see how we make sure you can integrate all necessary channels!

Kind regards,
Merijn
Technical Partner Manager Mollie
