### ISSUE TITLE
Can't install Mollie Plugin on Sylius 1.1.6 : knp-gaufrette-bundle dependency error

### ISSUE THREAD

**Issue by GreenItSolutions** [BitBagCommerce/SyliusMolliePlugin#3]
`
composer require bitbag/mollie-plugin -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
...
Loading plugin PackageVersions\Installer
Loading plugin Symfony\Thanks\Thanks
Running 1.6.3 (2018-01-31 16:28:17) with PHP 7.2.5-0ubuntu0.18.04.1 on Linux / 4.15.0-22-generic
...
Using version ^1.0 for bitbag/mollie-plugin
...
Dependency resolution completed in 0.023 seconds
Reading /root/.composer/cache/repo/https---packagist.org/provider-knplabs$knp-gaufrette-bundle.json from cache
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sylius/sylius v1.0.0 requires knplabs/knp-gaufrette-bundle ^0.3 -> satisfiable by knplabs/knp-gaufrette-bundle[0.3.0] but these conflict with your requirements or minimum-stability.
    - Installation request for bitbag/mollie-plugin ^1.0 -> satisfiable by bitbag/mollie-plugin[v1.0.0].
    - bitbag/mollie-plugin v1.0.0 requires sylius/sylius ^1.1 -> satisfiable by sylius/sylius[v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.1.6].
    - don't install sylius/sylius v1.1.0|remove sylius/sylius No version set (parsed as 1.0.0)
    - don't install sylius/sylius v1.1.1|remove sylius/sylius No version set (parsed as 1.0.0)
    - don't install sylius/sylius v1.1.2|remove sylius/sylius No version set (parsed as 1.0.0)
    - don't install sylius/sylius v1.1.3|remove sylius/sylius No version set (parsed as 1.0.0)
    - don't install sylius/sylius v1.1.4|remove sylius/sylius No version set (parsed as 1.0.0)
    - don't install sylius/sylius v1.1.5|remove sylius/sylius No version set (parsed as 1.0.0)
    - don't install sylius/sylius v1.1.6|remove sylius/sylius No version set (parsed as 1.0.0)
    - Installation request for sylius/sylius No version set (parsed as 1.0.0) -> satisfiable by sylius/sylius[No version set (parsed as 1.0.0)].

Installation failed, reverting ./composer.json to its original content.
`
Thanks in advance.

**Comment by GreenItSolutions** [comment]
Comment for myself (and others too)

MolliePlugin install is fine with Sylius Standard Edition but not with Developer Edition.

**Comment by damonsson** [comment]
From what you show. You are trying to install a plugin on a Sylius repo. You do not use the tag, only one of the branches (master? I think). That's why composer determined it was 1.0.0. Mollie plugin requires minimum version 1.1. You must switch branch to tag above 1.1 or use branch alias https://getcomposer.org/doc/articles/aliases.md
