### ISSUE TITLE
Fatal error on checkout: Argument 1 passed to Payum\Core\Gateway::addAction() must implement interface Payum\Core\Action\ActionInterface, string given

### ISSUE THREAD

**Issue by coderiekelt** [BitBagCommerce/SyliusMolliePlugin#4]
Hello,

I received the following error upon checkout:
Argument 1 passed to Payum\Core\Gateway::addAction() must implement interface Payum\Core\Action\ActionInterface, string given, called in D:\Code\sylius\vendor\payum\payum\src\Payum\Core\CoreGatewayFactory.php on line 219

I've followed the README.MD to the letter, and am unable to figure out what exactly is going wrong.

My specifications are as followed:
- PHP 7.2
- Windows 10
- MariaDB server

I'm testing using an Mollie test key.

**Comment by patrick477** [comment]
what's your symfony version?

**Comment by coderiekelt** [comment]
I'm currently using the latest version of Sylius, along with Symfony 4.1.4

**Comment by patrick477** [comment]
Closed due to 5a2903a.
