### ISSUE TITLE
product association not working after having installed the module

### ISSUE THREAD

**Issue by starmate** [BitBagCommerce/SyliusMolliePlugin#42]
Hello,

The following line in your app.js file is causing a conflict with product association form (from product edition page).
I had to replace:
`$('.ui.dropdown').dropdown();`

By:
`$('.ui.dropdown:not(.product-select)').dropdown();`

in order to make it work.

**Comment by daniel8702** [comment]
Hi @starmate, 
thanks for message, I think we resolve this problem on this line 

`if (!mollieFormIncluded) {
        return;
    }`

And the plugin should add 
`$('.ui.dropdown').dropdown();`
only when we use mollie form in admin panel. 

Which version of molly are You use?

**Comment by starmate** [comment]
Hi @daniel8702 ,

This is what I have in my composer.json:
"bitbag/mollie-plugin": "^3.2"

The thing is that the line 
`$('.ui.dropdown').dropdown();`
is in the middle of:
```
$(function () {
//...
});
```

`if (!mollieFormIncluded) { return; }`
In this case, would the above really be the soulution?

**Comment by daniel8702** [comment]
The currently installed version You can found in composer.lock. 

Use the newest version of mollie **v3.2.6** - recommended
The fix was added on 3.2.4

https://github.com/BitBagCommerce/SyliusMolliePlugin/compare/v3.2.4...v3.2.6

**Comment by starmate** [comment]
Ohh ok, thanks...
In this case, allow me to upgrade
Thanks for the info.

**Comment by starmate** [comment]
Hi @daniel8702 ,

v3.2.4 or v3.2.6 would require sylius/refund-plugin ^1.0.0-RC.3
I am currently using v3.2.3 of Mollie module.

`bitbag/mollie-plugin v3.2.6 requires sylius/refund-plugin ^1.0.0-RC.3 -> satisfiable by sylius/refund-plugin[1.0.x-dev, v1.0.0-RC.3] but these conflict with your requirements or minimum-stability.`

I prefer to use stable releases. Do you think that it is really necessary to upgrade to v2.3.6? Any major bug fix?

**Comment by daniel8702** [comment]
Hi @starmate,
I think You should update always to the newest version. We sometimes add some new features, and/or of course bugfix. 
In the mollie plugin, we use RefundPlugin to do the refund. This plugin is on RC release with necessary bugfix, 
we can not use the previous stable version of RfundPlugin. 
If You can add to you composer.json 

"prefer-stable": true,
"minimum-stability": "rc",

I hope this situation will not too long. Waiting for new stable release RefundPlugin :)
