### ISSUE TITLE
Missing Doctrine migration for MollieCustomer

### ISSUE THREAD

**Issue by SebLours** [BitBagCommerce/SyliusMolliePlugin#46]
The migration for MollieCustomer is missing:
`CREATE TABLE bitbag_mollie_customer (id INT AUTO_INCREMENT NOT NULL, profile_id VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_162C0BF1CCFA12B8 (profile_id), UNIQUE INDEX UNIQ_162C0BF1E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;`

**Comment by daniel8702** [comment]
Hi @SebLours, thanks for Your message. Could You create PR for this migration?
