### ISSUE TITLE
Missing inversed-by option in MollieGatewayConfig.orm.xml

### ISSUE THREAD

**Issue by matthiasvogl** [BitBagCommerce/SyliusMolliePlugin#50]
Hi,

the Many to One mapping for the Gatewayconfig should look like this.

        <many-to-one field="gateway" target-entity="Sylius\Bundle\PayumBundle\Model\GatewayConfigInterface" inversed-by="mollieGatewayConfig">
            <join-column name="gateway_id" referenced-column-name="id" nullable="true"/>
        </many-to-one>

![Bildschirmfoto vom 2020-10-02 11-58-29](https://user-images.githubusercontent.com/45167379/94911634-b99ba680-04a6-11eb-8349-48574c9f1b16.png)

Could you please fix this.

**Comment by MerijnMollie** [comment]
@daniel8702 could you please have a look? Thanks!
