### ISSUE TITLE
Stable release depends on sylius/refund-plugin RC

### ISSUE THREAD

**Issue by duckchip** [BitBagCommerce/SyliusMolliePlugin#61]
Hi guys,

It's impossible to install this module with the following `composer.json` configuration: `"prefer-stable": true`

The latest version of this module depends on a release candidate of "sylius/refund-plugin": "^1.0.0-RC.3" which is definitely a _no no_

I would have to do a composer hack in order to install the module.

Is this something that could be fixed?

Thx in advance!

**Comment by duckchip** [comment]
This issue is caused by https://github.com/BitBagCommerce/SyliusMolliePlugin/pull/27

**Comment by daniel8702** [comment]
Hi @duckchip, 

Thanks for Your message. 
We use RefundPlugin, there are bugs in the stable version that prevent the correct operation of refunds.

**Comment by duckchip** [comment]
hi @daniel8702 Could you point to which "bugs" you are referring to? So that we can follow up when the issues are resolved and then change the RC back to a stable version :) Thx!

**Comment by pottink** [comment]
Same here. Any updates or workarounds?

**Comment by pottink** [comment]
Solution:

Use the 'as' in your composer require section.

```
        "sylius/refund-plugin": "1.0.0-RC5 as 1.0.0",
```
