### ISSUE TITLE
Use DoctrineMigration 3

### ISSUE THREAD

**Issue by moafred** [BitBagCommerce/SyliusMolliePlugin#65]
Sylius 1.8 bring the great feature to delegate the migrations to the bundles instead of copy the migration in our apps, it will be nice if this bundle could benefit from it :)

[Here the documentation](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.8.md#migrations) from the upgrade note of Sylius.
And an [example of the update of the Refund plugin](https://github.com/Sylius/InvoicingPlugin/blob/master/src/DependencyInjection/SyliusInvoicingExtension.php#L33) in order to be compliant with the new DoctrineMigrations.

Note that it's a breaking change since it's need to use Sylius 1.8.

**Comment by daniel8702** [comment]
Hi @moafred, thanks for Your message. 

When we support plugin on sylius version 1.8 and higher then we change the migration.
But many thanks for Your suggestion.
