### ISSUE TITLE
Unknown column default_category_id in bitbag_mollie_configuration table

### ISSUE THREAD

**Issue by TheoNetemedia** [BitBagCommerce/SyliusMolliePlugin#86]
Hello,

I think there is an issue in the **3.3.5** version of the plugin when used with Sylius **1.8.5**.

The table `bitbag_mollie_configuration` has a `default_category` field used by the [one-to-one defaultCategory relationship](https://github.com/BitBagCommerce/SyliusMolliePlugin/blob/v3.3.5/src/Resources/config/doctrine/MollieGatewayConfig.orm.xml#L43). It seems I can create a Mollie payment method fine, but when try to access the edit page for the payment the page crashes with the following error:

```
An exception occurred while executing
'SELECT t0.method_id AS method_id_1, t0.name AS name_2, t0.enabled AS enabled_3, t0.image AS image_4, t0.minimum_amount AS minimum_amount_5, t0.maximum_amount AS maximum_amount_6, t0.payment_type AS payment_type_7, t0.country AS country_8, t0.can_refunded AS can_refunded_9, t0.issuers AS issuers_10, t0.country_restriction AS country_restriction_11, t0.country_level_excluded AS country_level_excluded_12, t0.country_level_allowed AS country_level_allowed_13, t0.order_expiration AS order_expiration_14, t0.payment_description AS payment_description_15, t0.id AS id_16, t0.payment_surcharge_fee AS payment_surcharge_fee_17, t0.method_image_id AS method_image_id_18, t0.default_category_id AS default_category_id_19, t0.gateway_id AS gateway_id_20 FROM bitbag_mollie_configuration t0 WHERE t0.gateway_id = ?'
with params [7]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.default_category_id' in 'field list'
```

Doing the following modification _seems_ to fix the issue:

```
   <one-to-one field="defaultCategory" target-entity="BitBag\SyliusMolliePlugin\Entity\ProductType" inversed-by="mollieGatewayConfig">
       <cascade>
           <cascade-persist/>
           <cascade-remove/>
       </cascade>
+      <join-column name="default_category"/>
   </one-to-one>
```

But I'm not really sure if this is indeed a real bug or if something went wrong in my project as this relationship has been in the package for quite some time now and nobody never had this issue.

**Comment by TheoNetemedia** [comment]
Note: I'm going to report this other DB-related issue here to not spam multiple DB issues on the repo.

I think there is another issue with another field in the DB: the [installation instructions, step 4](https://github.com/BitBagCommerce/SyliusMolliePlugin/blob/v3.3.5/doc/installation.md) indicates a `abandonedEmail` field for the Order entity that will be translated into an `abandoned_email` column in the DB. But the [migrations files](https://github.com/BitBagCommerce/SyliusMolliePlugin/blob/v3.3.5/migrations/Version20201021101147.php#L26) creates an `abandonedEmail` field instead.

Because of that, on the front-end side I'm now unable to add a product to the cart because the app throws the following error:

```
An exception occurred while executing
'INSERT INTO sylius_order (number, notes, state, checkout_completed_at, items_total, adjustments_total, total, created_at, updated_at, currency_code, locale_code, checkout_state, payment_state, shipping_state, token_value, customer_ip, channel_id, promotion_coupon_id, customer_id, abandoned_email, shipping_address_id, billing_address_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, null, \"cart\", null, 250000, 0, 250000, \"2021-02-02 09:52:28\", \"2021-02-02 09:52:28\", \"EUR\", \"fr_FR\", \"cart\", \"cart\", \"cart\", null, null, 1, null, null, 0, null, null]:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'abandoned_email' in 'field list'
```

Again I do not know if this is an issue with the package or if something went wrong on my side.

**Comment by daniel8702** [comment]
Hi @TheoNetemedia, thanks for Your message, 
Did You run migrations after upgrade to the new version of the mollie plugin?

On the migrations we have 
`$this->addSql('ALTER TABLE bitbag_mollie_configuration ADD default_category INT DEFAULT NULL');`

**Comment by TheoNetemedia** [comment]
I did a fresh install of the plugin directly to 3.3.5 so it's not an upgrade on my side, but yes I did execute the migrations.

Maybe I explained the first issue wrongly: I do have a `default_category` column in my table `bitbag_mollie_configuration` which defaults to NULL, but the app is looking for a `default_category_id` column instead not `default_category`.

**Comment by daniel8702** [comment]
Should be fixed. I will create a new release.
