### ISSUE TITLE
Missing bitbag_admin_test_api_keys route

### ISSUE THREAD

**Issue by TheoNetemedia** [BitBagCommerce/SyliusMolliePlugin#89]
Hello,

On v3.3.6, the `admin/payment-methods/new/mollie` page throws the following exception:

```
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "bitbag_admin_test_api_keys" as such route does not exist.").
```

The custom `SyliusShopAdmin/PaymentMethod/_form.htm.twig` in this package was [recently updated](https://github.com/BitBagCommerce/SyliusMolliePlugin/commit/20afccd8c9ff055fc3a8965d7e3163bae0543d46#diff-012a95d63df9e9cc7c9d628ab3624c3c516e9ff9b912a0d6fce0bd800dbe2ce1) to add a link to a new route but it seems that the related route definition is missing from the package. Also the translation string is missing too, so it looks like this button shouldn't be here at all.

**Comment by daniel8702** [comment]
Hi @TheoNetemedia thanks for your message, 
has been fixed. In which case the correct template is in `tests/Application/templates/bundles/SyliusAdminBundle/PaymentMethod/_form.html.twig`
