### ISSUE TITLE
Call to a member function getMethod() on bool  (PaymentMethodCheckoutValidator.php )

### ISSUE THREAD

**Issue by ankahla** [BitBagCommerce/SyliusMolliePlugin#98]
Hi,
Recently I installed this cool plugin in a sylius project, but I had an error in a particular situation: when I am on mollie payment screen If I decide to change payment method by clicking on the link "payment methods" I am redirected correctly to the store to choose the payment method (with flash message saying that order is cancelled) then when I click on pay I get the error `Call to a member function getMethod() on bool`. 

Is this a configuration problem ? what can I do ?

payment methods link on mollie screen
![payment methods link on mollie screen](https://user-images.githubusercontent.com/4787799/109206985-db286200-77a8-11eb-96d1-68643c263c67.png)

Returning back to store from mollie screen
![Returning back to store from mollie screen](https://user-images.githubusercontent.com/4787799/109207009-e5e2f700-77a8-11eb-9b30-45f6d6fa2207.png)

Error when trying to pay with other method
![Error when trying to pay with other method](https://user-images.githubusercontent.com/4787799/109207038-f1362280-77a8-11eb-9a15-84a4bf8de05e.png)

**Comment by daniel8702** [comment]
Hi @ankahla 

Thanks for Your message. 
This issue was fixed on https://github.com/BitBagCommerce/SyliusMolliePlugin/issues/91 

At the beginning of the next week, I create a new release. 
The solution is on dev-master right now.
